Repository ToyVallet/swifty-frontend, pull requests merged in 2024-06, with the labels that each got.

#8 chore: yarn 버전 다운그레이드
  .npmrc
  .yarnrc
  .yarnrc.yml
  package.json
  packages/tailwind-config/postcss.config.js
  packages/ui/package.json
  yarn.lock
Labels: ✋ 의존성

#11 [TASK-181] chore(@swifty/shared-lib): customFetch를 서버에서도 쿠키를 담아보낼 수 있도록 변경
  apps/root-admin/src/app/(dashboard)/user/[id]/page.tsx
  apps/root-admin/src/app/(dashboard)/user/page.tsx
  apps/root-admin/src/app/components/user/user-info/user-state-button-list.tsx
  apps/root-admin/src/app/lib/util/clear-server-cache.ts
  apps/root-admin/src/app/lib/util/insert-cookie-in-request.ts
  packages/shared-lib/package.json
  packages/shared-lib/src/utils/custom-fetch.ts
  packages/shared-lib/src/utils/index.ts
  packages/shared-lib/src/utils/server/get-serverside-cookies.ts
  packages/shared-lib/src/utils/server/index.ts
  packages/shared-lib/src/utils/server/revalidate.ts
Labels: ⚙️ 리팩토링, ✨ 개선점, 💬 리뷰 요청

#17 [TASK-190] chore: 크로마틱 CI 작업
  .github/workflows/chromatic.yml
  .github/workflows/ci.yml
  .github/workflows/deploy-storybook-github-pages.yml
  .github/workflows/deploy.yml
  apps/user-web/package.json
  apps/user-web/src/components/common/form/form.tsx
  package.json
  packages/eslint-config/package.json
  packages/ui/package.json
  packages/ui/src/stories/button.stories.ts
  turbo.json
Labels: 📄 문서, 🥳 배포, 🧪 테스트

#25 [TASK-136]루트 어드민 error.tsx 추가
  apps/root-admin/src/app/error.module.css
  apps/root-admin/src/app/error.tsx
  apps/root-admin/src/app/login/page.tsx
  apps/root-admin/src/components/festival/button/festival-button-list.tsx
  apps/root-admin/src/components/ui/button/delete-button/index.tsx
  apps/root-admin/src/components/ui/tag/index.tsx
  apps/root-admin/src/components/ui/upload/index.tsx
  apps/root-admin/src/components/user/user-info/user-state-button-list.tsx
  apps/root-admin/src/lib/util/formatDate.ts
Labels: ⚙️ 리팩토링, 💬 리뷰 요청, 🔨 기능

#26 [TASK-128] 루트 어드민 알림 기능
  apps/root-admin/src/app/(dashboard)/festivals/[id]/[concert-id]/page.tsx
  apps/root-admin/src/app/layout.tsx
  apps/root-admin/src/app/login/page.tsx
  apps/root-admin/src/components/festival/button/festival-button-list.tsx
  apps/root-admin/src/components/festival/form/festival-create-form.tsx
  apps/root-admin/src/components/festival/form/festival-update-form.tsx
  apps/root-admin/src/components/index.tsx
  apps/root-admin/src/components/provider/index.ts
  apps/root-admin/src/components/provider/notification-provider.tsx
  apps/root-admin/src/components/ui/button/delete-button/index.tsx
  apps/root-admin/src/components/university/form/university-create-form.tsx
  apps/root-admin/src/components/university/form/university-host-create-form.tsx
  apps/root-admin/src/components/university/form/university-logo-update-form.tsx
  apps/root-admin/src/components/university/form/university-update-form.tsx
  apps/root-admin/src/components/user/user-info/user-state-button-list.tsx
  apps/root-admin/src/hooks/festival/use-concert-crud.ts
  apps/root-admin/src/hooks/festival/use-lineup-crud.ts
  apps/root-admin/src/hooks/use-pagination.ts
Labels: ✨ 개선점, 💬 리뷰 요청, 🔨 기능

#30 [TASK-184] chore: input 컴포넌트 공통화
  .github/workflows/chromatic.yml
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  apps/user-web/src/app/(backable)/layout.tsx
  apps/user-web/src/app/(backable)/login/layout.tsx
  apps/user-web/src/app/(backable)/login/page.tsx
  apps/user-web/src/components/common/navigation/index.tsx
  apps/user-web/src/components/login/index.ts
  apps/user-web/src/components/login/login-form.tsx
  apps/user-web/src/components/my-tickets/actions.ts
  apps/user-web/src/components/my-tickets/index.ts
  apps/user-web/src/components/my-tickets/qr-code.tsx
  apps/user-web/src/components/my-tickets/ticket-tool.tsx
  apps/user-web/src/components/my-tickets/ticket.tsx
  packages/ui/components.json
  packages/ui/package.json
  packages/ui/src/button/index.tsx
  packages/ui/src/card.tsx
  packages/ui/src/code.tsx
  packages/ui/src/form/index.tsx
  packages/ui/src/index.ts
  packages/ui/src/input/index.tsx
  packages/ui/src/input/label.tsx
  packages/ui/src/input/motion.ts
  packages/ui/src/lib/constants/index.ts
  packages/ui/src/lib/constants/transition.ts
  packages/ui/src/tailwind.css
  packages/ui/tsconfig.json
  yarn.lock
Labels: ⚙️ 리팩토링

#32 [TASK-204] feature(user-web): 로그인 페이지 추가
  apps/user-web/public/images/glass.jpeg
  apps/user-web/public/images/lineup/no-lineup-image.webp
  apps/user-web/public/images/swifty-text-logo.svg
  apps/user-web/public/sw.js
  apps/user-web/public/workbox-07a7b4f2.js
  apps/user-web/server.js
  apps/user-web/src/app/(backable)/login/page.tsx
  apps/user-web/src/app/globals.css
  apps/user-web/src/components/login/login-form.tsx
  packages/shared-lib/src/index.ts
  packages/ui/src/button/index.tsx
  packages/ui/src/input/index.tsx
  packages/ui/src/tailwind.css
Labels: 💬 리뷰 요청, 🔨 기능

#33 [TASK-224]유저 웹페이지 메인 페이지, 라인업 페이지 API 연결
  apps/user-web/.eslintignore
  apps/user-web/.eslintrc.js
  apps/user-web/next.config.mjs
  apps/user-web/server.js
  apps/user-web/src/api/get-is-logged-in.ts
  apps/user-web/src/api/get-is-user-info.ts
  apps/user-web/src/api/get-server-side-token.ts
  apps/user-web/src/api/index.ts
  apps/user-web/src/api/response.ts
  apps/user-web/src/app/(backable)/festival/[id]/page.tsx
  apps/user-web/src/app/(root)/all-festivals/page.tsx
  apps/user-web/src/app/(root)/layout.tsx
  apps/user-web/src/app/(root)/page.tsx
  apps/user-web/src/app/action.ts
  apps/user-web/src/components/common/carousel/tile.tsx
  apps/user-web/src/components/common/floating-ticket.tsx
  apps/user-web/src/components/common/form/phone/index.tsx
  apps/user-web/src/components/common/hero/hero-tile.tsx
  apps/user-web/src/components/common/index.ts
  apps/user-web/src/components/common/side-nav/auth-group.tsx
  apps/user-web/src/components/common/side-nav/index.tsx
  apps/user-web/src/components/common/side-nav/nav-link.tsx
  apps/user-web/src/components/festival/line-up-section/index.tsx
  apps/user-web/src/components/festival/line-up-section/line-up-card.tsx
  apps/user-web/src/components/home/festival-tile.tsx
  apps/user-web/src/components/home/need-reverification-tile.tsx
  apps/user-web/src/components/ticketing/card.tsx
  apps/user-web/src/components/ticketing/form.tsx
  apps/user-web/src/components/ticketing/index.ts
  apps/user-web/src/hooks/index.ts
  apps/user-web/src/hooks/use-auth.ts
  apps/user-web/src/lib/constants.ts
  apps/user-web/src/lib/mock/data.ts
  apps/user-web/src/lib/types/apit.ts
  apps/user-web/src/lib/types/festival.ts
  apps/user-web/src/lib/types/index.ts
  apps/user-web/src/lib/types/line-up.ts
  apps/user-web/src/store/auth-store.ts
  apps/user-web/tsconfig.json
Labels: ⚙️ 리팩토링, 💬 리뷰 요청
