Repository ToyVallet/swifty-frontend, pull requests merged in 2024-01, with the labels that each got.

#2 vscode 관련 이슈 해결
  .vscode/settings.json
Labels: 🏭 세팅

#3 Vanilla Extract 세팅
  .yarn/install-state.gz
  apps/swifty-bank/.eslintrc.js
  apps/swifty-bank/README.md
  apps/swifty-bank/app/globals.css
  apps/swifty-bank/app/layout.tsx
  apps/swifty-bank/app/page.css.ts
  apps/swifty-bank/app/page.tsx
  apps/swifty-bank/next-env.d.ts
  apps/swifty-bank/next.config.js
  apps/swifty-bank/package.json
  apps/swifty-bank/tsconfig.json
  apps/web/app/favicon.ico
  apps/web/app/page.module.css
  apps/web/app/page.tsx
  apps/web/next.config.js
  apps/web/public/circles.svg
  apps/web/public/next.svg
  apps/web/public/turborepo.svg
  apps/web/public/vercel.svg
  package-lock.json
  yarn.lock
Labels: 🏭 세팅

#6 Heading 컴포넌트 개발
  .yarn/install-state.gz
  apps/swifty-bank/app/page.tsx
  package.json
  packages/ui/src/heading/heading.css.ts
  packages/ui/src/heading/index.tsx
  packages/ui/src/index.ts
Labels: 🔨 기능

#12 docs(readme): readme 수정
  README.md
Labels: 📄 문서

#16 feat: 글로벌 스타일 세팅
  .yarn/install-state.gz
  apps/swifty-bank/app/globals.css
  apps/swifty-bank/app/layout.tsx
  apps/swifty-bank/app/page.css.ts
  apps/swifty-bank/app/page.tsx
  package.json
  packages/ui/package.json
  packages/ui/src/heading/heading.css.ts
  packages/ui/src/input/index.tsx
  packages/ui/src/input/input.css.ts
  packages/ui/src/styles/ThemeProvider.tsx
  packages/ui/src/styles/index.ts
  packages/ui/src/styles/vars.css.ts
  packages/ui/tsconfig.json
  yarn.lock
Labels: 🏭 세팅, 🎨 스타일

#11 feat: select 컴포넌트 생성
  .gitignore
  .yarn/install-state.gz
  apps/swifty-bank/app/page.tsx
  packages/ui/src/index.ts
  packages/ui/src/select/customStyles.ts
  packages/ui/src/select/index.tsx
  packages/ui/src/select/select.css.ts
  yarn.lock
Labels: 💬 리뷰 요청

#20 Button 컴포넌트 수정 (with review)
  packages/eslint-config/react-internal.js
  packages/ui/src/button/index.tsx
Labels: ⚙️ 리팩토링, ✨ 개선점
