Repository ToyVallet/swifty-frontend, pull requests merged in 2024-07, with the labels that each got.

#36 [TASK-223] tailwindcss 스타일 설정
  packages/tailwind-config/src/theme.ts
Labels: 🏭 세팅

#38 chore: 폰트 사이즈 리팩터링
  apps/user-web/src/app/error.tsx
  apps/user-web/src/app/global-error.tsx
  apps/user-web/src/app/not-found.tsx
  apps/user-web/src/components/admin/keypad/display.tsx
  apps/user-web/src/components/admin/keypad/keys.tsx
  apps/user-web/src/components/admin/result-tile/error.tsx
  apps/user-web/src/components/admin/result-tile/student-info.tsx
  apps/user-web/src/components/common/bottom-sheet/index.tsx
  apps/user-web/src/components/common/carousel/index.tsx
  apps/user-web/src/components/common/carousel/tile.tsx
  apps/user-web/src/components/common/footer.tsx
  apps/user-web/src/components/common/form/input.tsx
  apps/user-web/src/components/common/form/phone/index.tsx
  apps/user-web/src/components/common/form/phone/otp.tsx
  apps/user-web/src/components/common/form/terms.tsx
  apps/user-web/src/components/common/hero/hero-tile.tsx
  apps/user-web/src/components/common/menu-tiles/tile.tsx
  apps/user-web/src/components/common/navigation/index.tsx
  apps/user-web/src/components/festival/line-up-section/date-selector/date-block.tsx
  apps/user-web/src/components/festival/line-up-section/index.tsx
  apps/user-web/src/components/festival/line-up-section/line-up-card.tsx
  apps/user-web/src/components/festival/top-card.tsx
  apps/user-web/src/components/home/notice-tile.tsx
  apps/user-web/src/components/home/ticket-tile/index.tsx
  apps/user-web/src/components/home/tile-header.tsx
  apps/user-web/src/components/login/login-form.tsx
  apps/user-web/src/components/signup/header.tsx
  apps/user-web/src/components/ui/accordion.tsx
  apps/user-web/src/components/ui/card.tsx
  apps/user-web/src/components/ui/dropdown-menu.tsx
  apps/user-web/src/components/ui/input-otp.tsx
  apps/user-web/src/components/ui/select.tsx
  apps/user-web/src/components/ui/sheet.tsx
  apps/user-web/src/components/ui/table.tsx
  packages/ui/src/form/index.tsx
  packages/ui/src/input/index.tsx
  packages/ui/src/input/label.tsx
Labels: ⚙️ 리팩토링, 💬 리뷰 요청

#34 [TASK-222]feature(user-web): 약관 동의 아코디언 구현
  apps/user-web/public/icons/chceck.svg
  apps/user-web/server.js
  apps/user-web/src/app/(backable)/layout.tsx
  apps/user-web/src/app/(backable)/signup/page.tsx
  apps/user-web/src/components/signup/index.ts
  apps/user-web/src/components/signup/terms-of-service-accordion-item.tsx
  apps/user-web/src/components/signup/terms-of-service.tsx
  apps/user-web/src/components/ui/accordion.tsx
  apps/user-web/src/lib/constants.ts
  packages/tailwind-config/src/theme.ts
Labels: 💬 리뷰 요청, 🔨 기능

#40 [TASK-238] feat(user-web): 404 페이지 추가
  apps/user-web/public/icons/caution.svg
  apps/user-web/src/app/not-found.tsx
Labels: 💬 리뷰 요청, 🔨 기능

#42 [TASK-239] feat(user-web): 루트 에러 페이지 추가
  apps/user-web/public/icons/sad-file.svg
  apps/user-web/src/app/error.tsx
  apps/user-web/src/app/global-error.tsx
Labels: 💬 리뷰 요청, 🔨 기능

#53 [TASK-266] layout단 `react-hook-form` 추가
  apps/user-web/src/app/(backable)/signup/layout.tsx
  apps/user-web/src/app/(backable)/signup/schema.ts
Labels: 🔨 기능

#52 [TASK-267] 패스워드 아이콘 추가
  packages/ui/icon/eye-cross.svg
  packages/ui/icon/eye.svg
  packages/ui/src/input/index.tsx
  packages/ui/svg.d.ts
  packages/ui/tsconfig.json
  yarn.lock
Labels: 💬 리뷰 요청, 🔨 기능

#54 [TASK-266] feat(ui): 라디오 버튼 그룹추가
  apps/user-web/src/app/(backable)/signup/@identification/page.tsx
  packages/ui/src/index.ts
  packages/ui/src/radio-group/index.tsx
Labels: 💬 리뷰 요청, 🔨 기능

#49 [TASK-257] 바텀 select sheet 추가
  apps/user-web/package.json
  apps/user-web/public/icons/bottom-arrow.svg
  apps/user-web/src/components/common/bottom-sheet/index.tsx
  apps/user-web/src/components/common/bottom-sheet/motion.ts
  apps/user-web/src/components/common/index.ts
  apps/user-web/src/components/common/select/index.tsx
  apps/user-web/src/components/ui/select.tsx
  yarn.lock
Labels: ⚙️ 리팩토링, 🔨 기능

#57 [TASK-269] chore: 테일윈드 세팅
  apps/user-web/next.config.mjs
  apps/user-web/src/app/globals.css
  apps/user-web/src/app/layout.tsx
  apps/user-web/src/components/common/form/phone/index.tsx
  apps/user-web/tailwind.config.js
  apps/user-web/tailwind.config.ts
  apps/user-web/tsconfig.json
  package.json
  packages/eslint-config/package.json
  packages/tailwind-config/package.json
  packages/tailwind-config/src/index.ts
  packages/tailwind-config/src/plugins.ts
  packages/tailwind-config/src/theme.ts
  packages/tailwind-config/tailwind.config.ts
  packages/typescript-config/nextjs.json
  packages/typescript-config/package.json
  packages/ui/package.json
  packages/ui/src/tailwind.css
  packages/ui/tailwind.config.js
  packages/ui/tailwind.config.ts
  yarn.lock
Labels: 🏭 세팅, 💬 리뷰 요청

#60 [TASK-205]feat : 회원가입 로직 추가
  .gitignore
  .yarn/releases/yarn-4.2.2.cjs
  .yarnrc.yml
  apps/user-web/src/app/(backable)/signup/@account/page.tsx
  apps/user-web/src/app/(backable)/signup/@identification/page.tsx
  apps/user-web/src/app/(backable)/signup/@terms/data.ts
  apps/user-web/src/app/(backable)/signup/@terms/page.tsx
  apps/user-web/src/app/(backable)/signup/context.tsx
  apps/user-web/src/app/(backable)/signup/layout.tsx
  apps/user-web/src/app/(backable)/signup/schema.ts
  apps/user-web/src/components/home/ticket-tile/ticket-button.tsx
  apps/user-web/src/components/login/login-form.tsx
  apps/user-web/src/components/signup/account/id-check.tsx
  apps/user-web/src/components/signup/account/id.tsx
  apps/user-web/src/components/signup/account/password-confirm.tsx
  apps/user-web/src/components/signup/account/password.tsx
  apps/user-web/src/components/signup/form-error-control.tsx
  apps/user-web/src/components/signup/identification/carrier-with-nationality.tsx
  apps/user-web/src/components/signup/identification/date-of-birth.tsx
  apps/user-web/src/components/signup/identification/name.tsx
  apps/user-web/src/components/signup/identification/phone-number.tsx
  apps/user-web/src/components/signup/identification/sex.tsx
  apps/user-web/src/components/signup/identification/sms-code.tsx
  apps/user-web/src/components/signup/index.ts
  apps/user-web/src/components/signup/terms-of-service/types.ts
  apps/user-web/src/hooks/index.ts
  apps/user-web/src/hooks/use-interval.ts
  apps/user-web/src/lib/constants.ts
  packages/shared-lib/src/constants/index.ts
  packages/shared-lib/src/utils/format/dateOfBirth.ts
  packages/shared-lib/src/utils/format/index.ts
  packages/ui/src/input/index.tsx
Labels: 💬 리뷰 요청, 🔨 기능

#63 [TASK-281] user-web 학적 인증 구현
  apps/user-web/public/icons/file.svg
  apps/user-web/public/icons/magnifier.svg
  apps/user-web/public/images/cer-example.jpg
  apps/user-web/src/app/(backable)/signup/@account/page.tsx
  apps/user-web/src/app/(backable)/signup/@complete/page.tsx
  apps/user-web/src/app/(backable)/signup/@identification/page.tsx
  apps/user-web/src/app/(backable)/signup/@terms/page.tsx
  apps/user-web/src/app/(backable)/signup/context.tsx
  apps/user-web/src/app/(backable)/signup/layout.tsx
  apps/user-web/src/app/(backable)/univ-certification/@certification/page.tsx
  apps/user-web/src/app/(backable)/univ-certification/@complete/page.tsx
  apps/user-web/src/app/(backable)/univ-certification/@example/page.tsx
  apps/user-web/src/app/(backable)/univ-certification/context.tsx
  apps/user-web/src/app/(backable)/univ-certification/layout.tsx
  apps/user-web/src/app/(backable)/univ-certification/schema.ts
  apps/user-web/src/app/context/step-context.tsx
  apps/user-web/src/components/common/fixed-bottom-cta-group.tsx
  apps/user-web/src/components/common/fixed-bottom-cta.tsx
  apps/user-web/src/components/common/index.ts
  apps/user-web/src/components/common/search/index.tsx
  apps/user-web/src/components/login/login-form.tsx
  apps/user-web/src/components/signup/account/id-check.tsx
  apps/user-web/src/components/signup/header.tsx
  apps/user-web/src/components/univ-certification/certification/index.ts
  apps/user-web/src/components/univ-certification/certification/student-certification-image.tsx
  apps/user-web/src/components/univ-certification/certification/student-status.tsx
  apps/user-web/src/components/univ-certification/example/example-image.tsx
  apps/user-web/src/components/univ-certification/example/index.ts
  apps/user-web/src/components/univ-certification/example/univ-search.tsx
  apps/user-web/src/components/univ-certification/index.tsx
  apps/user-web/src/hooks/index.ts
  apps/user-web/src/hooks/use-debounce.ts
  apps/user-web/src/lib/constants.ts
  apps/user-web/src/lib/types/certification.ts
  packages/shared-lib/src/constants/index.ts
  packages/ui/src/input/index.tsx
  packages/ui/src/select/index.tsx
Labels: 💬 리뷰 요청, 🔨 기능

#68 [TASK-281] user-web 학적 인증 디자인 수정 반영
  apps/user-web/src/app/(backable)/univ-certification/@certification/page.tsx
  apps/user-web/src/app/(backable)/univ-certification/@example/page.tsx
  apps/user-web/src/app/(backable)/univ-certification/layout.tsx
  apps/user-web/src/components/univ-certification/certification/index.ts
  apps/user-web/src/components/univ-certification/certification/ocr/index.tsx
  apps/user-web/src/components/univ-certification/certification/ocr/ocr-drawer.tsx
  apps/user-web/src/components/univ-certification/certification/ocr/ocr-input.tsx
  apps/user-web/src/components/univ-certification/certification/student-certification-image.tsx
  apps/user-web/src/components/univ-certification/example/example-image.tsx
  apps/user-web/src/components/univ-certification/example/index.ts
  packages/tailwind-config/tailwind.config.ts
Labels: ⚙️ 리팩토링

#70 [TASK-293] user-web 티켓팅 문제 수정
  apps/root-admin/src/middleware.ts
  apps/user-web/src/app/(backable)/change-phone-number/complete/page.tsx
  apps/user-web/src/app/(backable)/change-phone-number/page.tsx
  apps/user-web/src/app/(backable)/signup/@account/page.tsx
  apps/user-web/src/app/(backable)/signup/@identification/page.tsx
  apps/user-web/src/app/(backable)/signup/context.tsx
  apps/user-web/src/app/(backable)/signup/layout.tsx
  apps/user-web/src/app/(backable)/signup/schema.ts
  apps/user-web/src/app/(root)/all-festivals/page.tsx
  apps/user-web/src/app/(root)/layout.tsx
  apps/user-web/src/components/common/global-navigation/index.tsx
  apps/user-web/src/components/common/search/index.tsx
  apps/user-web/src/components/festival/line-up-section/date-selector/date-block.tsx
  apps/user-web/src/components/festival/line-up-section/index.tsx
  apps/user-web/src/components/festival/line-up-section/line-up-card.tsx
  apps/user-web/src/components/signup/identification/date-of-birth.tsx
  apps/user-web/src/components/signup/identification/gender.tsx
  apps/user-web/src/components/signup/identification/index.ts
  apps/user-web/src/components/signup/identification/sms-code.tsx
  apps/user-web/src/lib/constants.ts
  apps/user-web/src/middleware.tsx
  packages/shared-lib/src/utils/format/dateOfBirth.ts
  packages/shared-lib/src/utils/server/get-cookie-value.ts
  packages/shared-lib/src/utils/server/index.ts
  packages/ui/src/input/index.tsx
Labels: ⚙️ 리팩토링, ✨ 개선점

#73 [TASK-287] feat: 검색기능 완성
  apps/user-web/src/app/(backable)/layout.tsx
  apps/user-web/src/app/(backable)/search/page.tsx
  apps/user-web/src/components/search/index.ts
  apps/user-web/src/components/search/search-input.tsx
  apps/user-web/src/components/search/search-result/index.tsx
  apps/user-web/src/components/search/search-result/item.tsx
  apps/user-web/src/hooks/use-debounce.ts
Labels: 💬 리뷰 요청, 🔨 기능

#85 [TASK-307] chore: 쿠키 함수 리팩토링
  apps/root-admin/src/api/check-status-for-RefreshToken.ts
  apps/root-admin/src/api/index.ts
  apps/root-admin/src/api/is-expired-refresh.ts
  apps/root-admin/src/components/ui/button/logout-button.tsx
  apps/root-admin/src/lib/util/cookies.ts
  apps/root-admin/src/lib/util/index.ts
  apps/root-admin/src/middleware.ts
  apps/user-web/middleware.ts
  apps/user-web/src/app/(backable)/mypage/change-password/@complete/page.tsx
  apps/user-web/src/app/(backable)/mypage/delete/@complete/page.tsx
  apps/user-web/src/app/(backable)/mypage/delete/@noti/page.tsx
  apps/user-web/src/components/common/global-navigation/index.tsx
  apps/user-web/src/components/mypage/logout/index.tsx
  apps/user-web/src/hooks/use-client-side-token.ts
  apps/user-web/src/middleware.tsx
  packages/shared-lib/src/utils/custom-fetch.ts
  packages/shared-lib/src/utils/server/cookie.ts
  packages/shared-lib/src/utils/server/delete-cookie.ts
  packages/shared-lib/src/utils/server/get-cookie-value.ts
  packages/shared-lib/src/utils/server/get-serverside-cookies.ts
  packages/shared-lib/src/utils/server/index.ts
  packages/shared-lib/src/utils/server/logout.ts
Labels: ⚙️ 리팩토링, ✨ 개선점, 💬 리뷰 요청

#88 [TASK-308] chore(root-admin): 날짜 선택 범위 제한 제거
  apps/root-admin/src/components/festival/form/concert-create-form.tsx
  apps/root-admin/src/components/festival/form/festival-create-form.tsx
  apps/root-admin/src/components/festival/form/festival-update-form.tsx
  apps/root-admin/src/lib/index.ts
  apps/root-admin/src/lib/util/index.ts
  apps/root-admin/src/lib/util/over-current-day.ts
  packages/shared-lib/src/constants/index.ts
  packages/shared-lib/src/constants/remotes/host-admin.ts
  packages/shared-lib/src/constants/remotes/index.ts
  packages/shared-lib/src/constants/remotes/root-admin.ts
  packages/shared-lib/src/utils/http.ts
Labels: ✨ 개선점

#91 [TASK-313] 로깅 시스템 구축
  apps/root-admin/src/app/(dashboard)/error.tsx
  apps/root-admin/src/app/(dashboard)/page.tsx
  apps/root-admin/src/app/(dashboard)/university/page.tsx
  apps/root-admin/src/app/error.tsx
  apps/root-admin/src/components/index.tsx
  apps/root-admin/src/components/log/flush-button.tsx
  apps/root-admin/src/components/log/index.ts
  apps/root-admin/src/components/log/log-table.tsx
  apps/root-admin/src/components/ui/button/delete-button/index.tsx
  apps/root-admin/src/hooks/use-pagination.ts
  apps/root-admin/src/types/api.ts
  apps/user-web/src/app/error.tsx
  packages/shared-lib/src/constants/remotes/root-admin.ts
  packages/shared-lib/src/types/utility.ts
  packages/shared-lib/src/utils/index.ts
  packages/shared-lib/src/utils/log.ts
Labels: 🔨 기능

#92 [TASK-313] feat(root-admin): 로깅 시스템 추가
  apps/root-admin/src/app/(dashboard)/error.tsx
  apps/root-admin/src/app/(dashboard)/page.tsx
  apps/root-admin/src/components/festival/button/open-hidden-toggle.tsx
  apps/root-admin/src/components/log/badge.tsx
  apps/root-admin/src/components/log/index.ts
  apps/root-admin/src/components/log/log-detail-drawer.module.css
  apps/root-admin/src/components/log/log-detail-drawer.tsx
  apps/root-admin/src/components/log/log-source-toggle.tsx
  apps/root-admin/src/components/log/log-table.module.css
  apps/root-admin/src/components/log/log-table.tsx
  apps/root-admin/src/components/ui/logo/index.tsx
  apps/root-admin/src/components/user/table/index.tsx
  apps/root-admin/src/hooks/use-pagination.ts
  packages/shared-lib/src/utils/http.ts
  packages/shared-lib/src/utils/log.ts
Labels: 🔨 기능

#94 [TASK-296] root admin 보강
  apps/root-admin/src/app/(dashboard)/festivals/[id]/[concert-id]/page.tsx
  apps/root-admin/src/app/(dashboard)/festivals/page.tsx
  apps/root-admin/src/app/(dashboard)/page.tsx
  apps/root-admin/src/app/(dashboard)/university/[id]/page.tsx
  apps/root-admin/src/app/(dashboard)/university/university.module.css
  apps/root-admin/src/app/(dashboard)/user/[id]/page.tsx
  apps/root-admin/src/components/festival/button/open-hidden-toggle.tsx
  apps/root-admin/src/components/festival/form/concert-update-form.tsx
  apps/root-admin/src/components/festival/form/festival-create-form.tsx
  apps/root-admin/src/components/festival/form/festival-update-form.tsx
  apps/root-admin/src/components/festival/status-notifier/index.tsx
  apps/root-admin/src/components/log/download.tsx
  apps/root-admin/src/components/log/index.ts
  apps/root-admin/src/components/log/log-detail-drawer.tsx
  apps/root-admin/src/components/university/detail/button-list/button-list.module.css
  apps/root-admin/src/components/university/detail/button-list/index.tsx
  apps/root-admin/src/components/university/detail/festivals/university-festival.module.css
  apps/root-admin/src/components/university/detail/host-user/host-user.module.css
  apps/root-admin/src/components/university/detail/host-user/index.tsx
  apps/root-admin/src/components/university/detail/index.tsx
  apps/root-admin/src/components/university/form/university-host-create-form.tsx
  apps/root-admin/src/components/university/table/host-user-table.tsx
  apps/root-admin/src/components/university/table/university-table.tsx
  apps/root-admin/src/components/user/table/index.tsx
  apps/root-admin/src/components/user/user-info/index.tsx
  apps/root-admin/src/components/user/user-info/user-state-button-list.tsx
  apps/root-admin/src/components/user/user-info/userInfo.module.css
  apps/root-admin/src/hooks/festival/use-concert-crud.ts
  apps/root-admin/src/hooks/festival/use-lineup-crud.ts
  apps/root-admin/src/lib/constant/index.ts
  apps/root-admin/src/types/concert.ts
  apps/root-admin/src/types/festival.ts
  apps/root-admin/src/types/university.ts
  apps/root-admin/src/types/user.ts
  apps/user-web/src/components/common/search/index.tsx
  packages/shared-lib/src/constants/remotes/root-admin.ts
  packages/shared-lib/src/utils/http.ts
Labels: ✨ 개선점, 🔨 기능

#96 [TASK-322] tailwindcsss light dark mode
  apps/root-admin/src/components/festival/form/lineup-update-form.tsx
  apps/root-admin/src/components/festival/lineup-card/index.tsx
  apps/root-admin/src/types/lineup.ts
  apps/user-web/.eslintignore
  apps/user-web/src/app/(backable)/login/layout.tsx
  apps/user-web/src/app/(backable)/login/page.tsx
  apps/user-web/src/app/(root)/page.tsx
  apps/user-web/src/app/globals.css
  apps/user-web/src/components/common/carousel/tile.tsx
  apps/user-web/src/components/common/footer.tsx
  apps/user-web/src/components/common/global-navigation/icon-link.tsx
  apps/user-web/src/components/common/global-navigation/index.tsx
  apps/user-web/src/components/common/hero/index.tsx
  apps/user-web/src/components/common/navigation/index.tsx
  apps/user-web/src/components/common/navigation/logo-link.tsx
  apps/user-web/src/components/festival/line-up-section/index.tsx
  apps/user-web/src/components/festival/line-up-section/line-up-card.tsx
  apps/user-web/src/components/home/festival-tile.tsx
  apps/user-web/src/components/login/login-form.tsx
  apps/user-web/src/components/mypage/schedule-section/index.tsx
  apps/user-web/src/lib/types/festival.ts
  apps/user-web/src/lib/types/line-up.ts
  packages/assets/src/icons/common/arrow-left.svg
  packages/assets/src/icons/common/category.svg
  packages/assets/src/icons/common/home.svg
  packages/assets/src/icons/common/lock.svg
  packages/assets/src/icons/common/search.svg
  packages/assets/src/icons/common/swifty-full-logo.svg
  packages/assets/src/icons/common/user.svg
  packages/tailwind-config/tailwind.config.ts
  packages/ui/src/button/index.tsx
  packages/ui/src/drawer/index.tsx
  packages/ui/src/form/index.tsx
  packages/ui/src/input/index.tsx
  packages/ui/src/input/label.tsx
  packages/ui/src/radio-group/index.tsx
  packages/ui/src/select/index.tsx
  packages/ui/src/tailwind.css
  packages/ui/src/toast/index.tsx
  packages/ui/tailwind.config.ts
Labels: 🏭 세팅

#97 [TASK-292] 티켓팅 입장 제약 작성
  .github/workflows/CD for Dev Environment.yml
  apps/root-admin/src/components/festival/lineup-card/index.tsx
  apps/user-web/src/app/(backable)/festival/[id]/page.tsx
  apps/user-web/src/app/(backable)/festival/[id]/ticketing/@date/page.tsx
  apps/user-web/src/app/(backable)/signup/@account/page.tsx
  apps/user-web/src/app/(backable)/signup/@terms/data.ts
  apps/user-web/src/app/(backable)/signup/@terms/page.tsx
  apps/user-web/src/app/(backable)/signup/schema.ts
  apps/user-web/src/app/(backable)/ticketing-result/[id]/page.tsx
  apps/user-web/src/app/(backable)/verification/student/@example/page.tsx
  apps/user-web/src/app/not-authorized/page.tsx
  apps/user-web/src/components/common/menu-tiles/index.tsx
  apps/user-web/src/components/festival/ticketing/date-select.tsx
  apps/user-web/src/components/verification/student/certification/ocr/ocr-drawer.tsx
  apps/user-web/src/components/verification/student/example/univ-search.tsx
  apps/user-web/src/lib/types/certification.ts
  packages/shared-lib/src/constants/remotes/user-api.ts
Labels: ✨ 개선점, 🔨 기능

#100 [TASK-328] 디자인 오류 수정
  apps/user-web/src/app/(backable)/find/id/@name/page.tsx
  apps/user-web/src/app/(backable)/find/id/@phone/page.tsx
  apps/user-web/src/app/(backable)/find/id/layout.tsx
  apps/user-web/src/app/(backable)/find/password/@id/page.tsx
  apps/user-web/src/app/(backable)/find/password/@password/page.tsx
  apps/user-web/src/app/(backable)/find/password/@phone/page.tsx
  apps/user-web/src/app/(backable)/signup/layout.tsx
  apps/user-web/src/components/mypage/logout/index.tsx
  apps/user-web/src/components/signup/terms-of-service/items.tsx
  packages/ui/src/input/index.tsx
Labels: ✨ 개선점, 🐞 버그

#102 [TASK-328] 회원 탈퇴 css 추가 수정
  apps/user-web/src/app/(backable)/mypage/delete/layout.tsx
Labels: 🐞 버그

#103 [TASK-329] swifty docker setting
  apps/root-admin/Dockerfile
  apps/root-admin/next.config.mjs
  apps/root-admin/package.json
  apps/user-web/Dockerfile
  apps/user-web/package.json
  docker-compose.yml
  yarn.lock
Labels: 🐞 버그, 🥳 배포

#98 [TASK-292] github aciton yml 파일 수정
  .github/workflows/CD for Dev Environment.yml
  apps/user-web/package.json
  apps/user-web/public/images/ticket/ticket-wating.gif
  apps/user-web/src/app/(backable)/festival/[id]/ticketing/@check/page.tsx
  apps/user-web/src/app/(backable)/festival/[id]/ticketing/@date/page.tsx
  apps/user-web/src/app/(backable)/festival/[id]/ticketing/@wait/page.tsx
  apps/user-web/src/app/(backable)/festival/[id]/ticketing/context.tsx
  apps/user-web/src/app/(backable)/festival/[id]/ticketing/layout.tsx
  apps/user-web/src/app/(backable)/festival/[id]/ticketing/schema.ts
  apps/user-web/src/app/(backable)/find/password/@password/page.tsx
  apps/user-web/src/app/(backable)/find/password/layout.tsx
  apps/user-web/src/app/(backable)/mypage/change-password/@newPassword/page.tsx
  apps/user-web/src/app/(backable)/signup/@complete/page.tsx
  apps/user-web/src/app/(backable)/signup/layout.tsx
  apps/user-web/src/app/(backable)/ticketing-result/[id]/page.tsx
  apps/user-web/src/app/(backable)/verification/status/page.tsx
  apps/user-web/src/app/(backable)/verification/student/schema.ts
  apps/user-web/src/app/layout.tsx
  apps/user-web/src/components/common/captcha/index.tsx
  apps/user-web/src/components/common/index.ts
  apps/user-web/src/components/festival/ticketing/check/ticket-description.tsx
  apps/user-web/src/components/festival/ticketing/check/ticket-fixed-cta.tsx
  apps/user-web/src/components/festival/ticketing/check/ticket-info.tsx
  apps/user-web/src/components/festival/ticketing/check/top-card.tsx
  apps/user-web/src/components/festival/ticketing/date-select.tsx
  apps/user-web/src/components/festival/ticketing/date/index.tsx
  apps/user-web/src/components/festival/ticketing/index.ts
  apps/user-web/src/components/mypage/change-phone-number/index.tsx
  apps/user-web/src/components/verification/status/index.tsx
  apps/user-web/src/components/verification/student/certification/student-certification-image.tsx
  apps/user-web/src/lib/types/certification.ts
  packages/assets/src/icons/user-web/index.ts
  packages/assets/src/icons/user-web/ticketing/calender.svg
  packages/assets/src/icons/user-web/ticketing/time.svg
  packages/ui/src/input/index.tsx
  packages/ui/src/radio-group/index.tsx
  yarn.lock
Labels: 🏭 세팅
