Repository ToyVallet/swifty-frontend, pull requests merged in 2024-02, with the labels that each got.

#18 Input 컴포넌트 수정
  apps/swifty-bank/app/page.css.ts
  apps/swifty-bank/app/page.tsx
  packages/hooks/src/useId.ts
  packages/ui/package.json
  packages/ui/src/input/index.tsx
  packages/ui/src/input/input.css.ts
  yarn.lock
Labels: 💬 리뷰 요청, 🔨 기능

#21 feat: 기본 레이아웃 스타일 설정
  .yarn/install-state.gz
  apps/swifty-bank/app/layout.css.ts
  apps/swifty-bank/app/layout.tsx
Labels: 🏭 세팅, 💬 리뷰 요청, 🎨 스타일

#24 jest 설정
  README.md
  package.json
  packages/hooks/jest.config.js
  packages/hooks/package.json
  packages/hooks/tsconfig.jest.json
  packages/jest-config/README.md
  packages/jest-config/index.js
  packages/jest-config/package.json
  packages/ui/jest.config.js
  packages/ui/package.json
  packages/ui/tsconfig.jest.json
  yarn.lock
Labels: 🏭 세팅

#26 바텀시트 컴포넌트
  apps/swifty-bank/app/page.tsx
  packages/hooks/src/index.ts
  packages/hooks/src/useBottomSheet.ts
  packages/hooks/src/useWindowDimensions.ts
  packages/ui/src/bottom-sheet/bottom-sheet.css.ts
  packages/ui/src/bottom-sheet/index.tsx
  packages/ui/src/bottom-sheet/motion.ts
  packages/ui/src/bottom-sheet/overlay.tsx
  packages/ui/src/bottom-sheet/types.ts
  packages/ui/src/heading/heading.css.ts
  packages/ui/src/heading/index.tsx
  packages/ui/src/index.ts
  packages/ui/src/styles/vars.css.ts
Labels: 🔨 기능

#25 회원가입 약관 동의, 약관 상세
  .yarn/install-state.gz
  apps/swifty-bank/app/agreement/_component/AgreementBtn.tsx
  apps/swifty-bank/app/agreement/_component/agreementBtn.css.ts
  apps/swifty-bank/app/agreement/detail/page.css.ts
  apps/swifty-bank/app/agreement/detail/page.tsx
  apps/swifty-bank/app/agreement/page.css.ts
  apps/swifty-bank/app/agreement/page.tsx
  apps/swifty-bank/public/icon/Icon_Cancellation.svg
  apps/swifty-bank/public/img/agreement/Symbol_Agree.png
  apps/swifty-bank/public/img/agreement/Symbol_Agree.webp
Labels: 💬 리뷰 요청, 🔨 기능, 🎨 스타일

#27 jest 설정
  packages/jest-config/index.js
  packages/jest-config/package.json
  packages/ui/src/button/button.test.tsx
  yarn.lock
Labels: ✨ 개선점, 🏭 세팅, 💬 리뷰 요청

#30 레이아웃 세팅
  apps/swifty-bank/app/layout.css.ts
  packages/ui/src/bottom-sheet/bottom-sheet.css.ts
Labels: 💬 리뷰 요청

#32 sms 인증화면 개발
  .yarn/install-state.gz
  apps/swifty-bank/app/sms-verification/_component/SmsVerification.css.ts
  apps/swifty-bank/app/sms-verification/_component/SmsVerificationInput.tsx
  apps/swifty-bank/app/sms-verification/page.css.ts
  apps/swifty-bank/app/sms-verification/page.tsx
  apps/swifty-bank/tsconfig.json
  yarn.lock
Labels: 💬 리뷰 요청, 🔨 기능

#22 feat: signin/form 페이지 구현
  apps/swifty-bank/app/signup/components/Ellipse.tsx
  apps/swifty-bank/app/signup/form/page.css.ts
  apps/swifty-bank/app/signup/form/page.tsx
  apps/swifty-bank/app/signup/lib/constants/tsp.ts
  apps/swifty-bank/app/signup/lib/validate/isActiveButton.ts
  apps/swifty-bank/app/signup/lib/validate/validator.ts
  apps/swifty-bank/public/icon/Icon_Ellipse.svg
  package.json
  packages/hooks/src/index.ts
  packages/hooks/src/useInput.ts
  packages/ui/src/button/index.tsx
  packages/ui/src/index.ts
  packages/ui/src/select/customStyles.ts
  packages/ui/src/select/index.tsx
  packages/ui/src/select/select.css.ts
Labels: 💬 리뷰 요청, 🔨 기능

#31 feat: 약관 동의 페이지 바텀시트 연동
  apps/swifty-bank/app/_constant/path.ts
  apps/swifty-bank/app/agreement/_component/AgreementBtn.tsx
  apps/swifty-bank/app/agreement/detail/page.tsx
  apps/swifty-bank/app/signup/_component/agreement-button/AgreementButton.tsx
  apps/swifty-bank/app/signup/_component/agreement-button/agreementButton.css.ts
  apps/swifty-bank/app/signup/_component/check-form/CheckForm.tsx
  apps/swifty-bank/app/signup/_component/check-form/checkForm.css.ts
  apps/swifty-bank/app/signup/_component/checkDetail/CheckDetail.tsx
  apps/swifty-bank/app/signup/_component/checkDetail/checkDetail.css.ts
  apps/swifty-bank/app/signup/_component/detail/detail-type.ts
  apps/swifty-bank/app/signup/_component/detail/detail.css.ts
  apps/swifty-bank/app/signup/_component/detail/index.tsx
  apps/swifty-bank/app/signup/_component/detail/motion.ts
  apps/swifty-bank/app/signup/page.css.ts
  apps/swifty-bank/app/signup/page.tsx
  apps/swifty-bank/next.config.js
  apps/swifty-bank/package.json
  apps/swifty-bank/public/icon/rightIcon.svg
  apps/swifty-bank/tsconfig.json
  packages/hooks/package.json
  packages/ui/package.json
  packages/ui/src/check/check.css.ts
  packages/ui/src/check/index.tsx
  packages/ui/src/icon/checkIcon.svg
  packages/ui/src/icon/nonCheckIcon.svg
  packages/ui/src/icon/rightIcon.svg
  packages/ui/src/index.ts
  packages/ui/tsconfig.json
  packages/ui/type/type.d.ts
  yarn.lock
Labels: 💬 리뷰 요청, 🔨 기능
