Repository ToyVallet/swifty-frontend, pull requests merged in 2024-03, with the labels that each got.

#40 Button UI 수정
  apps/swifty-bank/app/_utils/type.ts
  apps/swifty-bank/app/layout.tsx
  apps/swifty-bank/app/page.tsx
  apps/swifty-bank/app/signup/_component/agreement-button/AgreementButton.tsx
  apps/swifty-bank/app/signup/_component/check-form/CheckForm.tsx
  apps/swifty-bank/app/signup/_component/checkDetail/CheckDetail.tsx
  apps/swifty-bank/app/signup/_component/detail/Detail.tsx
  apps/swifty-bank/app/signup/_component/detail/detail-type.ts
  apps/swifty-bank/app/signup/_lib/constants/tsp.ts
  apps/swifty-bank/app/signup/_lib/validate/isActiveButton.ts
  apps/swifty-bank/app/signup/_lib/validate/validator.ts
  apps/swifty-bank/app/signup/form/page.tsx
  packages/ui/src/button/button.css.ts
  packages/ui/src/button/index.tsx
  packages/ui/src/button/motion.ts
Labels: ⚙️ 리팩토링, 💬 리뷰 요청, 🎨 스타일

#42 Toast/kd02109
  apps/swifty-bank/app/page.tsx
  packages/ui/src/index.ts
  packages/ui/src/toast/index.tsx
  packages/ui/src/toast/motion.ts
  packages/ui/src/toast/toast.css.ts
Labels: 💬 리뷰 요청, 🔨 기능

#48 setting: auth, user, sms, keypad api 인터페이스 셋팅
  apps/swifty-bank/app/_api/api.ts
  apps/swifty-bank/app/_api/auth.ts
  apps/swifty-bank/app/_api/keypad.ts
  apps/swifty-bank/app/_api/sms.ts
  apps/swifty-bank/app/_api/type.ts
  apps/swifty-bank/app/_api/url.ts
  apps/swifty-bank/app/_api/user.ts
  apps/swifty-bank/app/_api/utils.ts
Labels: 🏭 세팅, 💬 리뷰 요청, 📞 API

#50 fix: url 오타 수정 & credentials 설정 위치 수정
  apps/swifty-bank/app/_api/auth.ts
  apps/swifty-bank/app/_api/keypad.ts
  apps/swifty-bank/app/_api/sms.ts
  apps/swifty-bank/app/_api/type.ts
  apps/swifty-bank/app/_api/url.ts
  apps/swifty-bank/app/_api/user.ts
  apps/swifty-bank/app/_api/utils.ts
Labels: 🐞 버그, 💬 리뷰 요청, 📞 API

#49 Keypad/kd02109
  .yarn/install-state.gz
  apps/swifty-bank/app/_component/keypad/Key.tsx
  apps/swifty-bank/app/_component/keypad/KeyPad.tsx
  apps/swifty-bank/app/_component/keypad/keypad.css.ts
  apps/swifty-bank/app/_hook/useKeyPad.ts
  apps/swifty-bank/app/signup/password/_component/KeyPadLayout.tsx
  apps/swifty-bank/app/signup/password/_component/keyPadLayout.css.ts
  apps/swifty-bank/app/signup/password/page.tsx
  apps/swifty-bank/public/icon/Icon_Back_Black.svg
  apps/swifty-bank/public/icon/Icon_Back_Gray.svg
  apps/swifty-bank/public/icon/Icon_Cancellation_Gray.svg
  packages/ui/src/button/index.tsx
  packages/ui/src/button/motion.ts
  yarn.lock
Labels: 🔨 기능

#52 feat : Bottom Tap
  apps/swifty-bank/app/(bottomTab)/_component/BottomTab.tsx
  apps/swifty-bank/app/(bottomTab)/_component/ExchangeIcon.tsx
  apps/swifty-bank/app/(bottomTab)/_component/HomeIcon.tsx
  apps/swifty-bank/app/(bottomTab)/_component/MypageIcon.tsx
  apps/swifty-bank/app/(bottomTab)/_component/bottomTab.css.ts
  apps/swifty-bank/app/(bottomTab)/_type/type.ts
  apps/swifty-bank/app/(bottomTab)/account/page.tsx
  apps/swifty-bank/app/(bottomTab)/home/page.tsx
  apps/swifty-bank/app/(bottomTab)/layout.tsx
  apps/swifty-bank/app/(bottomTab)/mypage/page.tsx
Labels: 🔨 기능
